import Head from "next/head";
import Footer from "./Footer";

import Header from "./Header";

export default function Layout({ children, home, posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header home={home} posts={posts} />
      <div>{children}</div>
      <Footer />
    </div>
  );
}
