import Head from "next/head";
import Footer from "./Footer";

import Header from "./Header";

export default function Layout({ children, home, posts, tags }) {
  return (
    <div>
      <Head>
        <title>Spando</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/brand-circle.svg" />
      </Head>
      <Header home={home} posts={posts} tags={tags} />
      <div>{children}</div>
      <Footer />
    </div>
  );
}
